import assert from 'node:assert/strict';
import { realpath } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';

import { canonicalizeSync } from '../lib/utils/canonicalize.js';
import { makeTmpDir } from './_helpers.js';

test('canonicalizeSync resolves an existing path through realpath', async () => {
  const { cleanup, dir } = await makeTmpDir();

  try {
    // eslint-disable-next-line security/detect-non-literal-fs-filename, n/no-sync -- temp path generated by the test helper
    assert.equal(canonicalizeSync(dir), await realpath(path.resolve(dir)));
  } finally {
    await cleanup();
  }
});

test('canonicalizeSync falls back to resolved path when realpath fails', async () => {
  const { cleanup, dir } = await makeTmpDir();

  try {
    const missing = path.join(dir, 'missing', 'path');
    // eslint-disable-next-line n/no-sync
    assert.equal(canonicalizeSync(missing), path.resolve(missing));
  } finally {
    await cleanup();
  }
});
